version: "3"

services:
  dev-proxy:
    build: ./
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=stg.the-internal.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: dev-proxy
